--Creating the tables

CREATE TABLE UsersTable (
    UID       SERIAL        PRIMARY KEY,
    USERNAME  VARCHAR(50)   NOT NULL UNIQUE,
    PASSWORD  VARCHAR(50)   NOT NULL,
    USER_TYPE VARCHAR(10)   NOT NULL CHECK (USER_TYPE IN ('BUYER','SELLER'))
);

CREATE TABLE BuyersTable (
    UID           INT          PRIMARY KEY,
    STREET_NAME   VARCHAR(50)  NOT NULL,
    BUILDING_NUM  INT          NOT NULL,
    CITY          VARCHAR(50)  NOT NULL,
    COUNTRY       VARCHAR(50)  NOT NULL,
    FOREIGN KEY (UID) REFERENCES UsersTable(UID) ON DELETE CASCADE
);

CREATE TABLE SellersTable (
    UID  INT  PRIMARY KEY,
    FOREIGN KEY (UID) REFERENCES UsersTable(UID) ON DELETE CASCADE
);

CREATE TABLE ItemsTable (
    SERIAL_NUMBER  SERIAL         PRIMARY KEY,
    ITEM_NAME      VARCHAR(50)    NOT NULL,
    PRICE          DECIMAL(10,2)  NOT NULL,
    CATEGORY       VARCHAR(20)    NOT NULL CHECK (CATEGORY IN ('CHILD','ELECTRIC','OFFICE','CLOTHING','OTHER')),
    UID            INT            NOT NULL,
    FOREIGN KEY (UID) REFERENCES SellersTable(UID) ON DELETE CASCADE
);

CREATE TABLE ShoppingCartsTable (
    CID        SERIAL        PRIMARY KEY,
    CART_DATE  VARCHAR(50)   NOT NULL,
    UID        INT           NOT NULL,
    FOREIGN KEY (UID) REFERENCES BuyersTable(UID) ON DELETE CASCADE
);

CREATE TABLE CartItemsTable (
    CID            INT  NOT NULL,
    SERIAL_NUMBER  INT  NOT NULL,
    PRIMARY KEY (CID, SERIAL_NUMBER),
    FOREIGN KEY (CID)           REFERENCES ShoppingCartsTable(CID) ON DELETE CASCADE,
    FOREIGN KEY (SERIAL_NUMBER) REFERENCES ItemsTable(SERIAL_NUMBER) ON DELETE CASCADE
);
